name: Check Secret Value

on:
  workflow_dispatch:

jobs:
  check_secret_value:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret value is 12345
        env:
          VAL_HACKS: ${{ secrets.VAL_HACKS }}
        run: |
          if [ "$VAL_HACKS" == "12345" ]; then
            echo "Authentication successful."
            echo "Date: $(date +"%Y-%m-%d %H:%M:%S")"
            echo "User: $USER"
          else
            echo "Authentication denied."
          fi
